name: devquiz
description: DevQuiz from NLW#5 by Rocketseat, developed with the original idea from Figma layout.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.10.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - database/

  uses-material-design: true
